### ISSUE TITLE
Use :rand instead of :random

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_pubsub#16]
We are depending on Elixir 1.2, aren't we?

**Comment by chrismccord** [comment]
yes

**Comment by adamkittelson** [comment]
I'm not seeing any direct uses of :random other than a seed at https://github.com/phoenixframework/phoenix_pubsub/blob/137481d901442618cb93f01b8f6dab4a6ebc66ec/lib/phoenix_pubsub/tracker.ex#L202 which isn't necessary since the Enum.random in the tracker module uses :rand under the hood. (Assuming :crypto.strong_rand_bytes doesn't need or use the seed from :random)

**Comment by josevalim** [comment]
Yup, it seems we can just remove that line then.
