### ISSUE TITLE
Unsubscribe all

### ISSUE THREAD

**Issue by icecapp** [phoenixframework/phoenix_pubsub#164]
Hi everyone

I am trying to trying to implement `Turn off presence tracking`, as in, purge subscriptions on both a topic and a process. As in:

1. Unsubscribe all processes from a topic
2. Unsubscribe a process from every topic it is subscribed to

My use case is a social network with a `Presence` implementation that goes as follows:

Each user has its own `user:id` and `user_presence:id` channels. On joining its own `user:id` channel, the process:

- `Presence.track`s itself on its own eponymously id'ed `user_presence:id` topic
- `PubSub.subscribe`s to its contacts’ `user_presence:id` topics

Current user process now receives presence diffs for all contacts.

Now I'd like to `Turn off presence tracking`

To do so, we need to

- Stop tracking current user (solved with `Presence.untrack`)
- Unsubscribe all processes from current user’s `user_presence:id` topic (`1.` above)
- Unsubscribe current user’s channel process from all its contacts' `user_presence:id` subscriptions (`2.` above)

I asked on the Phoenix Slack channel about `1.`, and @chrismccord mentioned the processes have to unsubscribe themselves

<https://elixir-lang.slack.com/archives/C03QQCV4H/p1633637539238300>

which I guess involves sending a message to all the subscribers. I'm just looking at this 

```elixir
iex(2)> Registry.lookup Chata.PubSub, "user_presence:2057977985293615104"
[{#PID<0.6558.0>, nil},{#PID<0.6572.0>, nil},{#PID<0.6590.0>, nil}]
```

thinking, "couldn't we just purge that mapping"? 

Then, for point `2.`, to unsubscribe the current process from all topics it's subscribed to, short of maintaining the subscription list externally, I figured I could query and unsubscribe directly from the `Registry` directly as such: 

```elixir
Enum.each(Registry.keys(Chata.PubSub, self()), fn
  "user_presence:" <> _ = topic ->
    PubSub.unsubscribe(Chata.PubSub, topic)
  _ ->
    :ok
end)
```

Are there any particular caveats to using `Registry` behind `PubSub` in this way?

And more generally, are there any better approaches to purging subscriptions in `PubSub` ?

**Comment by chrismccord** [comment]
Processes must unsubscribe themselves and our use of Registry is private details so you shouldn't access it directly. It's not super clear how your topics are structured and why every user has their own individual topic which every other user must subscribe to. Typically your topic with be scoped to some other thing, like a parent relationship, (team, organization, etc), and the *key* will be the user's id. In such a scenarios "stop tracking me" is handled entirely by `untrack` since folks are subscribed to the higher level relationship which won't include you any more. In any case, we don't accept feature or support requests on the issue tracker, but I hope that helps. Thanks!
