### ISSUE TITLE
:ets.lookup(nil, :subscribe) problem

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix_pubsub#86]
Hey @chrismccord !

Some folks are running into an issue the following issue. Given a supervision tree that looks like:

```elixir
    children = [
      supervisor(App.Endpoint, []),
      supervisor(Absinthe.Subscription, [App.Endpoint]),
    ]
```

The `Absinthe.Subscription` starts a set of proxy processes which, as part of their boot process, do:

```elixir
  def init({pubsub, shard}) d
    :ok = pubsub.subscribe(topic(shard))
    {:ok, %__MODULE__{pubsub: pubsub}}
  end
```

`pubsub` in this case is the `App.Endpoint`, per the argument to the `Absinthe.Subscription` child spec.

This produces the following error: 
```
=INFO REPORT==== 13-Jul-2017::15:12:30 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application frontend: Frontend.Application.start(:normal, []) returned an error: shutdown: failed to start child: Absinthe.Subscription
    ** (EXIT) shutdown: failed to start child: Absinthe.Subscription.ProxySupervisor
        ** (EXIT) shutdown: failed to start child: 1
            ** (EXIT) an exception was raised:
                ** (ArgumentError) argument error
                    (stdlib) :ets.lookup(nil, :subscribe)
                    (phoenix_pubsub) lib/phoenix/pubsub.ex:288: Phoenix.PubSub.call/3
                    (absinthe) lib/absinthe/subscription/proxy.ex:19: Absinthe.Subscription.Proxy.init/1
                    (stdlib) gen_server.erl:365: :gen_server.init_it/2
                    (stdlib) gen_server.erl:333: :gen_server.init_it/6
                    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I haven't run into this myself so it's possibly config related, but I'm having difficulty tracking down what might be wrong.

**Comment by benwilson512** [comment]
Related: https://github.com/absinthe-graphql/absinthe/issues/346#issuecomment-323524044

**Comment by skosch** [comment]
@chrismccord just confirmed that this was due to my endpoing config missing its `pubsub: ...` entry. Ben found [this line](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L473-L478) but because the whole `pubsub` was missing, and not just `pubsub[:name]` with `pubsub[:adapter]` being given, it didn't raise. It's not a huge deal, but a warning would be nice.

**Comment by chrismccord** [comment]
A couple things. One, as we've confirmed you need to have your pubsub server configured in your endpoint (or started standalone). 2nd you need to make sure the Absinthe worker is *after* your endpoint/pubsub supervisor in the children list. This ensures the pubsub server will be stated before absinthe tries to call it. Otherwise the race in starting could produce the same observed error.

**Comment by benwilson512** [comment]
Sure that's understood. I suppose my main point here is that if you call
App.Endpoint.subscribe without public configured it might be handy to raise
an error explicitly. Happy to PR.

**Comment by chrismccord** [comment]
Please do. You'll have to rescue arg error from ets, because ets

**Comment by josevalim** [comment]
Outdated with upcoming changes, thanks!
