### ISSUE TITLE
Possible issue with distributed heterogeneous nodes

### ISSUE THREAD

**Issue by pragdave** [phoenixframework/phoenix_pubsub#96]
I have two connected nodes. One runs a Phoenix app, the other is plain ol' Elixir. The Phoenix node has pubsub started automatically, as it is a dependncy. The latter manually starts PubSub.

The Phoenix node broadcasts a message:

~~~ elixir
          Phoenix.PubSub.broadcast!(
            Hangman.Connector,
            "hangman:game_stats",
            {:game_stats, "123", "cat", true, ~w{ a b c }}
          )
~~~

On the plain ol' Elixir node, I get an error:

~~~
14:27:13.889 [error] GenServer Hangman.Connector terminating
** (UndefinedFunctionError) function Phoenix.Channel.Server.fastlane/3 is undefined (module Phoenix.Channel.Server is not available)                 
    Phoenix.Channel.Server.fastlane([{#PID<0.277.0>, nil}], :none, {:game_stats, "123", "cat", true, ["a", "b", "c"]})                               
    (phoenix_pubsub) lib/phoenix/pubsub/local.ex:101: anonymous fn/7 in Phoenix.PubSub.Local.broadcast/6                                             
    (elixir) lib/enum.ex:2940: Enum.reduce_range_inc/4
    (phoenix_pubsub) lib/phoenix/pubsub/local.ex:100: Phoenix.PubSub.Local.broadcast/6                                                               
    (phoenix_pubsub) lib/phoenix/pubsub/pg2_server.ex:52: Phoenix.PubSub.PG2Server.handle_info/2                                                     
Last message: {:forward_to_local, Phoenix.Channel.Server, :none, "hangman:game_stats", {:game_stats, "123", "cat", true, ["a", "b", "c"]}}           
State: %{name: Hangman.Connector, pool_size: 4}
 ~~~

I'm guessing the problem is that the Phoenix side assumes the other side is a Phoenix app and passes the Phoenix.Channel.Server module as the fastline implementation (which doesn't exist on the POE node).

Is this bad config on my part?

Dave

**Comment by chrismccord** [comment]
There are a couple issues going in this case. First, the fastlaning from the channel side, and next the `%Phoenix.Socket.Broadcast{}` struct that is sent as part of channel broadcasts. Both will cause another node to not be happy receiving a message since the `Channel/Socket` code is not loaded. It's not as simple as extracting this code out because if we take a step back and look at our system, we will need something sitting between the incoming pubsub messages and our channel client messages. Some ideas around how to better solve this than you starting your own intercepting server(s) that subscribe to topics and relay messages started with this POC PR:
https://github.com/phoenixframework/phoenix_pubsub/pull/34/files

Meanwhile, we have an ongoing effort to rewrite Phoenix.PubSub (https://github.com/phoenixframework/firenest) as a distributed tooling library, part of which handles pubsub. We took the lessons learned here and solved them with a configurable "dispatcher" that can both handle fastlaning and intercepting messages. This would allow each node to handle message delivery differently on each side without an extra process in between.

So the answer today for Phoenix.PubSub is to have a process on the channel side receiving messages and converting those messages into local broadcasts that channel clients understand. This may seem like a lot of work, but it makes sense when you have a remote node broadcasting some data, most likely in a form that's not tailored to consumption by remote browser clients. So we have `channel_app <-> elixir_app` messages with rich data, and the channel app side converts whatever subset of messages into local channel broadcasts as it receives them. This becomes less work and more efficient in firenest, but it's still a work in progress so expect changes if you hop on board. Hope that helps clear things up!

**Comment by pragdave** [comment]
As a simple fix, could the fastlane handler be configured per client, and not once? That was when my nonphoenix client subscribes, it looks up the fastlane when the message is received, rather than having the sender supply it...

**Comment by chrismccord** [comment]
> As a simple fix, could the fastlane handler be configured per client, and not once?

That's what we do in firenest :) It's a bigger refactor to make this change on Phoenix.PubSub, especially since we are moving towards firenest for the future

**Comment by pragdave** [comment]
How close is firenest to being mostly usable? I'm writing a course, and although a trivial roll-your-own pubsub is probably 50 loc, I'd really prefer not to reinvent the wheel.
